const data = {
  users: [
    { id: 1, name: 'Alice', email: 'alice@example.com', age: 30 },
    { id: 2, name: 'Bob', email: 'bob@example.com', age: 25 },
    { id: 3, name: 'Charlie', email: 'charlie@example.com', age: 35 },
    { id: 4, name: 'David', email: 'david@example.com', age: 28 },
    { id: 5, name: 'Eve', email: 'eve@example.com', age: 22 },
    { id: 6, name: 'Frank', email: 'frank@example.com', age: 31 },
    { id: 7, name: 'Grace', email: 'grace@example.com', age: 27 },
    { id: 8, name: 'Hank', email: 'hank@example.com', age: 24 },
    { id: 9, name: 'Ivy', email: 'ivy@example.com', age: 29 },
    { id: 10, name: 'Jack', email: 'jack@example.com', age: 33 },
    { id: 11, name: 'Kathy', email: 'kathy@example.com', age: 26 },
    { id: 12, name: 'Leo', email: 'leo@example.com', age: 23 },
    { id: 13, name: 'Mona', email: 'mona@example.com', age: 32 },
    { id: 14, name: 'Nick', email: 'nick@example.com', age: 30 },
    { id: 15, name: 'Olivia', email: 'olivia@example.com', age: 28 },
    { id: 16, name: 'Paul', email: 'paul@example.com', age: 34 },
    { id: 17, name: 'Quinn', email: 'quinn@example.com', age: 29 },
    { id: 18, name: 'Rachel', email: 'rachel@example.com', age: 31 },
    { id: 19, name: 'Steve', email: 'steve@example.com', age: 27 },
    { id: 20, name: 'Tina', email: 'tina@example.com', age: 26 },
    { id: 21, name: 'Uma', email: 'uma@example.com', age: 24 },
    { id: 22, name: 'Victor', email: 'victor@example.com', age: 28 },
    { id: 23, name: 'Wendy', email: 'wendy@example.com', age: 33 }
  ],
  products: [
    { PID: 1, name: 'Product 1', price: 100, description: 'High-quality product with exceptional durability.' },
    { PID: 2, name: 'Product 2', price: 200, description: 'Innovative design and top-notch performance.' },
    { PID: 3, name: 'Product 3', price: 300, description: 'Reliable and efficient, perfect for everyday use.' },
    { PID: 4, name: 'Product 4', price: 400, description: 'Sleek and stylish, a must-have for modern users.' },
    { PID: 5, name: 'Product 5', price: 500, description: 'Compact and powerful, ideal for travel and work.' },
    { PID: 6, name: 'Product 6', price: 600, description: 'State-of-the-art technology with user-friendly features.' },
    { PID: 7, name: 'Product 7', price: 700, description: 'Versatile and robust, perfect for professionals.' },
    { PID: 8, name: 'Product 8', price: 800, description: 'Ergonomic design for maximum comfort and efficiency.' },
    { PID: 9, name: 'Product 9', price: 900, description: 'Energy-efficient and eco-friendly, great for the environment.' },
    { PID: 10, name: 'Product 10', price: 1000, description: 'Premium materials and advanced functionality.' },
    { PID: 11, name: 'Product 11', price: 1100, description: 'High performance and easy maintenance.' },
    { PID: 12, name: 'Product 12', price: 1200, description: 'Exceptional value and reliability.' },
    { PID: 13, name: 'Product 13', price: 1300, description: 'Cutting-edge features and sleek design.' },
    { PID: 14, name: 'Product 14', price: 1400, description: 'Compact size with powerful capabilities.' },
    { PID: 15, name: 'Product 15', price: 1500, description: 'High-quality craftsmanship and innovative design.' },
    { PID: 16, name: 'Product 16', price: 1600, description: 'Exceptional performance and user-friendly interface.' },
    { PID: 17, name: 'Product 17', price: 1700, description: 'Stylish and functional, perfect for any setting.' },
    { PID: 18, name: 'Product 18', price: 1800, description: 'Durable and reliable, designed to last.' },
    { PID: 19, name: 'Product 19', price: 1900, description: 'Compact and portable, easy to carry.' },
    { PID: 20, name: 'Product 20', price: 2000, description: 'Advanced features and sleek aesthetics.' },
    { PID: 21, name: 'Product 21', price: 2100, description: 'User-friendly and highly efficient.' },
    { PID: 22, name: 'Product 22', price: 2200, description: 'Exceptional quality and performance.' },
    { PID: 23, name: 'Product 23', price: 2300, description: 'Cutting-edge technology with reliable performance.' },
    { PID: 24, name: 'Product 24', price: 2400, description: 'Innovative design with powerful features.' }
  ]
};

module.exports = data;
